from django.db import models


class TTLockToken(models.Model):
    """Access token model used to maintain the token always updated"""

    access_token = models.CharField(max_length=64)
    refresh_token = models.CharField(max_length=64)
    expires_in = models.DateTimeField()


class Lock(models.Model):
    """Lock model used to associate the lock to the user (owner)"""

    ttlock_id = models.PositiveIntegerField(
        unique=True,
        db_index=True,
        editable=False,
        verbose_name="TTLock ID",
        help_text="Lock ID generated by TTLock",
    )
    owner = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="locks"
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Lock {self.ttlock_id}"
